# Configuraci\u00f3n de conexi\u00f3n a la base de datos usando variables de entorno
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d6r1udcr85hc73f5qdrg-a.oregon-postgres.render.com:5432/db_abimar2}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:db_abimar2_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:dj3buJKZu21WzaskUVo9dOvM9O7D81xf}


# Configuraci\u00f3n JPA para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Puerto din\u00e1mico para Render.com
server.port=${PORT:8080}

# Establece un contexto base para toda la app
server.servlet.context-path=/abimar/core
